services:
  users-api:
    build:
      context: .
      dockerfile: Backend/UsersAPI/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: Clinix
      Jwt__Audience: Clinix
      Appointments__BaseUrl: http://appointments-api:8080/
      Appointments__InternalApiKey: ${APPOINTMENTS_INTERNAL_API_KEY}
      InternalServices__ApiKey: ${USERS_INTERNAL_API_KEY}
      Aws__Region: ${AWS_REGION}
      Aws__S3BucketName: ${S3_BUCKET}
    restart: unless-stopped

  appointments-api:
    build:
      context: .
      dockerfile: Backend/AppointmentsAPI/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: Clinix
      Jwt__Audience: Clinix
      UsersApi__BaseUrl: http://users-api:8080/
      UsersApi__InternalApiKey: ${USERS_INTERNAL_API_KEY}
      ClinicalRecords__BaseUrl: http://users-api:8080/
      ClinicalRecords__InternalApiKey: ${USERS_INTERNAL_API_KEY}
      InternalServices__ApiKey: ${APPOINTMENTS_INTERNAL_API_KEY}
    depends_on:
      - users-api
    restart: unless-stopped

  chatbot-api:
    build:
      context: .
      dockerfile: Backend/ChatBotAPI/Dockerfile
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: Clinix
      Jwt__Audience: Clinix
      OpenAi__ApiKey: ${OPENAI_KEY}
    depends_on:
      - users-api
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - users-api
      - appointments-api
      - chatbot-api
    restart: unless-stopped
